services:
  database:
    image: postgres:15
    container_name: postgres-taskmanager
    environment:
      POSTGRES_DB: task-manager
      POSTGRES_USER: Flawden
      POSTGRES_PASSWORD: 08193216ZEro
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/task-manager
      SPRING_DATASOURCE_USERNAME: Flawden
      SPRING_DATASOURCE_PASSWORD: 08193216ZEro
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/changelog-master.yaml
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  postgres_data: